### ISSUE TITLE
No Transparent Window Interior in Ubuntu 14.04

### ISSUE THREAD

**Issue by NomNomCameron** [colinkeenan/silentcast#11]
Just installed silentcast on Ubuntu 14.04 (Unity) and when I select the option for "Transparent window interior" and click OK, the transparent window displays for a moment, then disappears and you can't bring it back up? On the window switcher from the launcher it shows that it's still open but it does not display at all

**Comment by colinkeenan** [comment]
I won't be able to work on this today, but should tomorrow. Please provide any other information you can think of - I don't have time now to figure out what would help me.

**Comment by colinkeenan** [comment]
I am much busier than normal. Without looking back at the code at all, it sounds to me as though it's disappearing when the script moves the window to the top left corner. I had it do that because otherwise it could hide behind another window.

Do you have more than one monitor?

**Comment by colinkeenan** [comment]
Try to comment out line 103 in genffcom - the one that uses wmctrl to move the transparent window: https://github.com/colinkeenan/silentcast/blob/master/genffcom#L103

**Comment by colinkeenan** [comment]
Is this still a problem?

**Comment by NomNomCameron** [comment]
I figured out that the transparent window indicator gets moved off screen initially. If you pres Alt + F7 and move it back you can see it and then select the area you want to use. I think you can also use  Alt + spacebar but haven't tried
