### ISSUE TITLE
Couldn't parse video size.

### ISSUE THREAD

**Issue by Trudko** [colinkeenan/silentcast#12]
Hi, I just tried to record something using transparent window, unfortunately it crashers.

Unity or Pantheon detected, switching indicators...
avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
[x11grab @ 0x15022a0] Couldn't parse video size.
:0.0+1920,61: Invalid argument
/home/peto/silentcast/ffcom: line 20: kill: (9323) - No such process
/usr/bin/silentcast: line 171:  4380 Terminated              python "$py_script_dir"/transparent_window.py \""$all_keys"\"
1
15
gif

**Comment by Seth-Johnson** [comment]
Can you paste line 12 from `$HOME/silentcast/ffcom`?  

The output of  

    xMax=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1  
and  

   xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2 | cut -d '_' -f1 

will also be useful. Thanks.

**Comment by Trudko** [comment]
avconv -f x11grab -s 0x553 -r 15 -i :0.0+1920,61 -c:v ffvhuff -an -y /home/peto/silentcast/temp.mkv & ffmpegPID=$!

There is no output for xMax=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1   command line just hangs and waits for my input. Maybe I am missing something?

The last is 1200

**Comment by colinkeenan** [comment]
I have not tried to work on Silentcast, but others have done some tweaking & I've released a new version. Please see if v2.1 solves this issue.
