### ISSUE TITLE
Doesn't seem to work in Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by DivineOmega** [colinkeenan/silentcast#18]
I receive the error `temp.mkv not found, so can't generate anything from it`.

When running from the command prompt, I noticed silentcast appears to be looking for `ffmpeg` but attempting to run `ffmpeg` in this verison of Ubuntu returns `ffmpeg: command not found`.

For a bit of research, it seems `avconv` is the alternative in this version of Ubuntu.

**Comment by DivineOmega** [comment]
After a bit of experimentation it seems changing the call to `ffmpeg` in the `genffcom` file is insufficient. I believe the syntax of `avconv` differs, unfortunately.

**Comment by Arkni** [comment]
From README:

- Ubuntu
    - If running Gnome, install [Topicons](https://extensions.gnome.org/extension/495/topicons/)
    - Install what you can with apt-get

            $ sudo apt-get install bash libav-tools imagemagick x11-xserver-utils xdotool wininfo wmctrl python-gobject python-cairo xdg-utils
            $ sudo ln -s /usr/bin/avconv /usr/bin/ffmpeg
   - Look for **Download "yad"** at [yad](http://www.ubuntuupdates.org/package/webupd8/trusty/main/base/yad),
   click the 32 bit or 64 bit version and let Software Center install it.

**Comment by DivineOmega** [comment]
I had missed out the creation of the symlink, however it has had no effect and I am still receiving the error `temp.mkv not found, so can't generate anything from it`.

**Comment by DivineOmega** [comment]
When ran from the command line, and selecting full screen capture, I received the following output.

```
jordan@azurite:~/.silentcast$ ./silentcast
/home/jordan/.silentcast
f
8
/home/jordan/silentcast
genffcom: line 222: ((: 0+1920
1680 > 1920
1680: syntax error in expression (error token is "1680 > 1920
1680")
genffcom: line 223: ((: 0+1200
1050 > 1200
1050: syntax error in expression (error token is "1050 > 1200
1050")
Unity detected, switching indicators...
avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
:0.0+0,0: Protocol not found
/home/jordan/silentcast/ffcom: line 20: kill: (7663) - No such process
1
8
gif
/home/jordan
```

**Comment by DivineOmega** [comment]
Looking at the following lines, they seem to reference the resolutions of my multi-monitor set-up.

```
genffcom: line 222: ((: 0+1920
1680 > 1920
1680: syntax error in expression (error token is "1680 > 1920
1680")
genffcom: line 223: ((: 0+1200
1050 > 1200
1050: syntax error in expression (error token is "1050 > 1200
1050")
```

Could silentcast and/or one of the tools it uses not correctly support multi-monitor?

**Comment by Arkni** [comment]
See #9 and #16

**Comment by DivineOmega** [comment]
Thanks.

**Comment by DivineOmega** [comment]
Just tested from master. The merging of PR #16 seems to have resolved the issue here. :smile:
