### ISSUE TITLE
No system tray icon on Plasma 5

### ISSUE THREAD

**Issue by wenLiangcan** [colinkeenan/silentcast#22]

**Comment by Seth-Johnson** [comment]
Reproduced. KDE changed how notifications work in plasma 5. I haven't quite
identified a fix yet but I think I will have one by the end of the day.

**Comment by Seth-Johnson** [comment]
PR #23 should fix this, at least for the time being. IMO this is a bug in yad as they haven't kept up with KDE 5's changes. There's no way I'm wading into SourceForge to report or fix it though..

**Comment by wenLiangcan** [comment]
@Seth-Johnson It works well now, thank you so much!
