### ISSUE TITLE
Is there a shortcut to stop?

### ISSUE THREAD

**Issue by Ginhing** [colinkeenan/silentcast#28]
Or a timeout option to stop?

**Comment by colinkeenan** [comment]
No, but they are good ideas. It may be a couple of months before I do anything serious with this. I don't think it's very hard to implement those ideas though. Maybe someone will before I get to it.

**Comment by colinkeenan** [comment]
I don't plan to create a shortcut to stop, but if you check the current README.md on the main page, I have provided instructions for stopping Silentcast using the keyboard in i3wm and KDE PLasma 5. If you need instructions for a different desktop, please open a new issue. I am going to close this issue.
