### ISSUE TITLE
missing dependencies xwininfo

### ISSUE THREAD

**Issue by 3nids** [colinkeenan/silentcast#43]
at least on fedora, `xwininfo` is missing in the dependencies.

**Comment by colinkeenan** [comment]
I think `xwininfo` is included in some other package of utilities on Fedora. Can you let me know what package has to be installed to get it?

**Comment by colinkeenan** [comment]
Also, it may depend on release, so what release of Fedora do use?

**Comment by colinkeenan** [comment]
Did you follow the instructions for Fedora:

`su -c 'yum localinstall --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'`

`sudo yum install bash ffmpeg ImageMagick xdotool wmctrl xdg-utils yad`
