### ISSUE TITLE
Silentcast creates black overlay blocking windows etc behind [Arch, openbox]

### ISSUE THREAD

**Issue by bertiebaggio** [colinkeenan/silentcast#53]
I've installed silentcast via the Arch user repository (AUR) under `openbox`.

When I run it, it creates a black overlay which takes up the area of a single monitor.

![Black overlay screenshot -- wide!](https://i.imgur.com/vHk47IH.jpg)

I'm not sure if this is a Silentcast issue or a packaging issue; if it's the latter I can mention this to the maintainer of the AUR or seek support there.

I've used silentcast before to great effect, but that was under Debian.

**Comment by bertiebaggio** [comment]
Further searching reveals this is probably the same as or similar to issue #8 

Other tools such as conky and peek (see below) are able to do transparency though, so I'm not 100% sure.

![peek example](https://user-images.githubusercontent.com/7524620/35979203-a5f19c32-0cdf-11e8-9e4d-0d3204334b8a.gif)

**Comment by colinkeenan** [comment]
I don't see the transparency in your example, but I know there are methods of providing transparency without a compositor. However, Silentcast requires a compositor. See the Arch Wiki about compositing with openbox: https://wiki.archlinux.org/index.php/openbox#Compositing_effects

**Comment by bertiebaggio** [comment]
Thank you for your response! The left-hand third of the screenshot (black with green text) is what is drawn by silentcast.

I haven't missed compositing until now and I wasn't aware silentcast required it; thank you for the info. I guess if someone else runs into this problem with Arch they'll know where to look and what to do.

I'll have a look at the options and either go with one of those or peek.

Cheers
