### ISSUE TITLE
remove mkv file after creating gif ?

### ISSUE THREAD

**Issue by souhaiebtar** [colinkeenan/silentcast#55]
@colinkeenan  thinks for this great tool (it's the only one that worked for me, thanks for that), it work great with archlux on openbox, is there a way using silentcast.conf to remove mkv after creating gif because it remain after creating the gif, anyway thanks again for your work.

**Comment by colinkeenan** [comment]
I have not built in that ability, and have become much too busy to work on this. I will keep this issue open though and if I work on it, I'll update.

**Comment by souhaiebtar** [comment]
@colinkeenan  thanks anyway
